[2021-07-02 14:30:03,766] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fusemachines_Airflow_project.prevalent_projects 2021-07-01T00:00:00+00:00 [queued]>
[2021-07-02 14:30:03,775] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: Fusemachines_Airflow_project.prevalent_projects 2021-07-01T00:00:00+00:00 [queued]>
[2021-07-02 14:30:03,775] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:30:03,776] {taskinstance.py:1068} INFO - Starting attempt 1 of 4
[2021-07-02 14:30:03,776] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-02 14:30:03,854] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): prevalent_projects> on 2021-07-01T00:00:00+00:00
[2021-07-02 14:30:03,856] {standard_task_runner.py:52} INFO - Started process 50224 to run task
[2021-07-02 14:30:03,861] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'Fusemachines_Airflow_project', 'prevalent_projects', '2021-07-01T00:00:00+00:00', '--job-id', '74', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzpov0jq0', '--error-file', '/tmp/tmpaaykdn6f']
[2021-07-02 14:30:03,861] {standard_task_runner.py:77} INFO - Job 74: Subtask prevalent_projects
[2021-07-02 14:30:05,092] {logging_mixin.py:104} INFO - Running <TaskInstance: Fusemachines_Airflow_project.prevalent_projects 2021-07-01T00:00:00+00:00 [running]> on host deepika-Inspiron-5570
[2021-07-02 14:30:05,322] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sthadpka93@gmail.com
AIRFLOW_CTX_DAG_OWNER=postgres
AIRFLOW_CTX_DAG_ID=Fusemachines_Airflow_project
AIRFLOW_CTX_TASK_ID=prevalent_projects
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-07-01T00:00:00+00:00
[2021-07-02 14:30:13,669] {logging_mixin.py:104} INFO - +------------+--------------+-----+
|country_code|      category|count|
+------------+--------------+-----+
|          NL|Product Design|  264|
|          MX|   Video Games|   85|
|          AT|Product Design|   58|
|          HK|Product Design|  217|
|          AU|Product Design|  697|
|          CA|Product Design| 1117|
|          GB|Product Design| 1839|
|          DE|Product Design|  425|
|          ES|   Video Games|  200|
|          US|Product Design|16193|
|          FR|           Web|  260|
|          CH|Product Design|  107|
|          SG|Product Design|  121|
|          IT|Product Design|  279|
|          SE|Product Design|  134|
|          JP|Product Design|    6|
|          NZ|Product Design|  105|
|          IE|           Web|   62|
|          BE|   Video Games|   48|
|          NO|           Web|   56|
|          LU|           Web|    6|
|          DK|Product Design|  129|
+------------+--------------+-----+
[2021-07-02 14:30:13,669] {logging_mixin.py:104} INFO - 
[2021-07-02 14:30:13,670] {taskinstance.py:1481} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1137, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/deepika/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/deepika/airflow/dags/dag.py", line 48, in prevalent_projects
    load_to_db(task7())
  File "/home/deepika/airflow/dags/main.py", line 22, in load_to_db
    df.write.jdbc(url=url,
AttributeError: 'NoneType' object has no attribute 'write'
[2021-07-02 14:30:13,684] {taskinstance.py:1524} INFO - Marking task as UP_FOR_RETRY. dag_id=Fusemachines_Airflow_project, task_id=prevalent_projects, execution_date=20210701T000000, start_date=20210702T084503, end_date=20210702T084513
[2021-07-02 14:30:16,200] {local_task_job.py:151} INFO - Task exited with return code 1
